<?php


declare(strict_types=1);

namespace App\Ami;

class AttendedTransfer extends Event {
    protected $eTable = 'e_attendedtransfer';
    protected $eventFields = [
        'Result' => ['dbField' => 'result'],
        'OrigTransfererChannel' => ['dbField' => 'origtransfererchannel'],
        'OrigTransfererChannelState' => ['dbField' => 'origtransfererchannelstate'],
        'OrigTransfererChannelStateDesc' => ['dbField' => 'origtransfererchannelstatedesc'],
        'OrigTransfererCallerIDNum' => ['dbField' => 'origtransferercalleridnum'],
        'OrigTransfererCallerIDName' => ['dbField' => 'origtransferercalleridname'],
        'OrigTransfererConnectedLineNum' => ['dbField' => 'origtransfererconnectedlinenum'],
        'OrigTransfererConnectedLineName' => ['dbField' => 'origtransfererconnectedlinename'],
        'OrigTransfererLanguage' => ['dbField' => 'origtransfererlanguage'],
        'OrigTransfererAccountCode' => ['dbField' => 'origtransfereraccountcode'],
        'OrigTransfererContext' => ['dbField' => 'origtransferercontext'],
        'OrigTransfererExten' => ['dbField' => 'origtransfererexten'],
        'OrigTransfererPriority' => ['dbField' => 'origtransfererpriority'],
        'OrigTransfererUniqueid' => ['dbField' => 'origtransfereruniqueid'],
        'OrigTransfererLinkedid' => ['dbField' => 'origtransfererlinkedid'],
        'OrigBridgeUniqueid' => ['dbField' => 'origbridgeuniqueid'],
        'OrigBridgeType' => ['dbField' => 'origbridgetype'],
        'OrigBridgeTechnology' => ['dbField' => 'origbridgetechnology'],
        'OrigBridgeCreator' => ['dbField' => 'origbridgecreator'],
        'OrigBridgeName' => ['dbField' => 'origbridgename'],
        'OrigBridgeNumChannels' => ['dbField' => 'origbridgenumchannels'],
        'OrigBridgeVideoSourceMode' => ['dbField' => 'origbridgevideosourcemode'],
        'OrigBridgeVideoSource' => ['dbField' => 'origbridgevideosource'],
        'SecondTransfererChannel' => ['dbField' => 'secondtransfererchannel'],
        'SecondTransfererChannelState' => ['dbField' => 'secondtransfererchannelstate'],
        'SecondTransfererChannelStateDesc' => ['dbField' => 'secondtransfererchannelstatedesc'],
        'SecondTransfererCallerIDNum' => ['dbField' => 'secondtransferercalleridnum'],
        'SecondTransfererCallerIDName' => ['dbField' => 'secondtransferercalleridname'],
        'SecondTransfererConnectedLineNum' => ['dbField' => 'secondtransfererconnectedlinenum'],
        'SecondTransfererConnectedLineName' => ['dbField' => 'secondtransfererconnectedlinename'],
        'SecondTransfererLanguage' => ['dbField' => 'secondtransfererlanguage'],
        'SecondTransfererAccountCode' => ['dbField' => 'secondtransfereraccountcode'],
        'SecondTransfererContext' => ['dbField' => 'secondtransferercontext'],
        'SecondTransfererExten' => ['dbField' => 'secondtransfererexten'],
        'SecondTransfererPriority' => ['dbField' => 'secondtransfererpriority'],
        'SecondTransfererUniqueid' => ['dbField' => 'secondtransfereruniqueid'],
        'SecondTransfererLinkedid' => ['dbField' => 'secondtransfererlinkedid'],
        'SecondBridgeUniqueid' => ['dbField' => 'secondbridgeuniqueid'],
        'SecondBridgeType' => ['dbField' => 'secondbridgetype'],
        'SecondBridgeTechnology' => ['dbField' => 'secondbridgetechnology'],
        'SecondBridgeCreator' => ['dbField' => 'secondbridgecreator'],
        'SecondBridgeName' => ['dbField' => 'secondbridgename'],
        'SecondBridgeNumChannels' => ['dbField' => 'secondbridgenumchannels'],
        'SecondBridgeVideoSourceMode' => ['dbField' => 'secondbridgevideosourcemode'],
        'SecondBridgeVideoSource' => ['dbField' => 'secondbridgevideosource'],
        'DestType' => ['dbField' => 'desttype'],
        'DestBridgeUniqueid' => ['dbField' => 'destbridgeuniqueid'],
        'DestApp' => ['dbField' => 'destapp'],
        'LocalOneChannel' => ['dbField' => 'localonechannel'],
        'LocalOneChannelState' => ['dbField' => 'localonechannelstate'],
        'LocalOneChannelStateDesc' => ['dbField' => 'localonechannelstatedesc'],
        'LocalOneCallerIDNum' => ['dbField' => 'localonecalleridnum'],
        'LocalOneCallerIDName' => ['dbField' => 'localonecalleridname'],
        'LocalOneConnectedLineNum' => ['dbField' => 'localoneconnectedlinenum'],
        'LocalOneConnectedLineName' => ['dbField' => 'localoneconnectedlinename'],
        'LocalOneLanguage' => ['dbField' => 'localonelanguage'],
        'LocalOneAccountCode' => ['dbField' => 'localoneaccountcode'],
        'LocalOneContext' => ['dbField' => 'localonecontext'],
        'LocalOneExten' => ['dbField' => 'localoneexten'],
        'LocalOnePriority' => ['dbField' => 'localonepriority'],
        'LocalOneUniqueid' => ['dbField' => 'localoneuniqueid'],
        'LocalOneLinkedid' => ['dbField' => 'localonelinkedid'],
        'LocalTwoChannel' => ['dbField' => 'localtwochannel'],
        'LocalTwoChannelState' => ['dbField' => 'localtwochannelstate'],
        'LocalTwoChannelStateDesc' => ['dbField' => 'localtwochannelstatedesc'],
        'LocalTwoCallerIDNum' => ['dbField' => 'localtwocalleridnum'],
        'LocalTwoCallerIDName' => ['dbField' => 'localtwocalleridname'],
        'LocalTwoConnectedLineNum' => ['dbField' => 'localtwoconnectedlinenum'],
        'LocalTwoConnectedLineName' => ['dbField' => 'localtwoconnectedlinename'],
        'LocalTwoLanguage' => ['dbField' => 'localtwolanguage'],
        'LocalTwoAccountCode' => ['dbField' => 'localtwoaccountcode'],
        'LocalTwoContext' => ['dbField' => 'localtwocontext'],
        'LocalTwoExten' => ['dbField' => 'localtwoexten'],
        'LocalTwoPriority' => ['dbField' => 'localtwopriority'],
        'LocalTwoUniqueid' => ['dbField' => 'localtwouniqueid'],
        'LocalTwoLinkedid' => ['dbField' => 'localtwolinkedid'],
        'DestTransfererChannel' => ['dbField' => 'desttransfererchannel'],
        'TransfereeChannel' => ['dbField' => 'transfereechannel'],
        'TransfereeChannelState' => ['dbField' => 'transfereechannelstate'],
        'TransfereeChannelStateDesc' => ['dbField' => 'transfereechannelstatedesc'],
        'TransfereeCallerIDNum' => ['dbField' => 'transfereecalleridnum'],
        'TransfereeCallerIDName' => ['dbField' => 'transfereecalleridname'],
        'TransfereeConnectedLineNum' => ['dbField' => 'transfereeconnectedlinenum'],
        'TransfereeConnectedLineName' => ['dbField' => 'transfereeconnectedlinename'],
        'TransfereeLanguage' => ['dbField' => 'transfereelanguage'],
        'TransfereeAccountCode' => ['dbField' => 'transfereeaccountcode'],
        'TransfereeContext' => ['dbField' => 'transfereecontext'],
        'TransfereeExten' => ['dbField' => 'transfereeexten'],
        'TransfereePriority' => ['dbField' => 'transfereepriority'],
        'TransfereeUniqueid' => ['dbField' => 'transfereeuniqueid'],
        'TransfereeLinkedid' => ['dbField' => 'transfereelinkedid'],
        'EventDt' => ['dbField' => 'eventdt'],
        'uTime' => ['dbField' => 'utime'],
        'instanceUuid' => ['dbField' => 'instanceuuid'],
    ];
}
